---
extends:
  - stylelint-config-standard-scss
  - stylelint-config-standard-vue/scss
plugins:
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
rules:
  # 标记 CSS 规范中未知的属性-值对
  declaration-property-value-no-unknown: true
  # 禁止空块
  block-no-empty: true
  # 在声明的块中中禁止出现重复的属性
  declaration-block-no-duplicate-properties: true
  # 颜色6位长度
  color-hex-length: long
  # 可能的情况下使用命名的颜色
  color-named: always-where-possible
  # 禁止使用无效的十六进制颜色
  color-no-invalid-hex: true
  # 兼容自定义标签名
  # selector-type-no-unknown:
  #   - true
  #   - ignoreTypes:
  #     -

  # 特性值必须使用引号
  selector-attribute-quotes: always
  # 忽略伪类选择器 ::v-deep
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - v-deep
  # 禁止低优先级的选择器出现在高优先级的选择器之后。
  no-descending-specificity: null
  # 禁止使用重复的字体名称
  font-family-no-duplicate-names: true
  # 每一个不是关键字的字体名都使用引号括起来
  font-family-name-quotes: always-unless-keyword
  # 不验证@未知的名字，为了兼容scss的函数
  at-rule-no-unknown: null
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
  # 禁止空注释
  comment-no-empty: true
  # 禁止使用由于其他属性的原因而被忽略的属性
  plugin/declaration-block-no-ignored-properties: true
  # 禁止使用可以缩写却不缩写的属性
  declaration-block-no-redundant-longhand-properties: true
  # 禁止缩写属性覆盖相关普通写法属性
  declaration-block-no-shorthand-property-overrides: true
  # 限制单行声明块中声明的数量
  declaration-block-single-line-max-declarations: 1
  # 禁止简写属性的冗余值
  shorthand-property-no-redundant-values: true
  # 禁止属性使用浏览器引擎前缀
  property-no-vendor-prefix: true
  # 禁止值的浏览器引擎前缀
  value-no-vendor-prefix: true
  # 禁止使用未知单位
  unit-no-unknown: true
  # 禁用 CSS 不支持的双斜线注释
  no-invalid-double-slash-comments: true
  # 属性的排序
  order/properties-order:
    - position
    - z-index
    - top
    - bottom
    - left
    - right
    - float
    - clear
    - columns
    - columns-width
    - columns-count
    - column-rule
    - column-rule-width
    - column-rule-style
    - column-rule-color
    - column-fill
    - column-span
    - column-gap
    - display
    - grid
    - grid-template-rows
    - grid-template-columns
    - grid-template-areas
    - grid-auto-rows
    - grid-auto-columns
    - grid-auto-flow
    - grid-column-gap
    - grid-row-gap
    - grid-template
    - grid-template-rows
    - grid-template-columns
    - grid-template-areas
    - grid-gap
    - grid-row-gap
    - grid-column-gap
    - grid-area
    - grid-row-start
    - grid-row-end
    - grid-column-start
    - grid-column-end
    - grid-column
    - grid-column-start
    - grid-column-end
    - grid-row
    - grid-row-start
    - grid-row-end
    - flex
    - flex-grow
    - flex-shrink
    - flex-basis
    - flex-flow
    - flex-direction
    - flex-wrap
    - justify-content
    - align-content
    - align-items
    - align-self
    - order
    - table-layout
    - empty-cells
    - caption-side
    - border-collapse
    - border-spacing
    - list-style
    - list-style-type
    - list-style-position
    - list-style-image
    - ruby-align
    - ruby-merge
    - ruby-position
    - box-sizing
    - width
    - min-width
    - max-width
    - height
    - min-height
    - max-height
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - border
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width
    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style
    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color
    - border-image
    - border-image-source
    - border-image-slice
    - border-image-width
    - border-image-outset
    - border-image-repeat
    - border-top
    - border-top-width
    - border-top-style
    - border-top-color
    - border-top
    - border-right-width
    - border-right-style
    - border-right-color
    - border-bottom
    - border-bottom-width
    - border-bottom-style
    - border-bottom-color
    - border-left
    - border-left-width
    - border-left-style
    - border-left-color
    - border-radius
    - border-top-right-radius
    - border-bottom-right-radius
    - border-bottom-left-radius
    - border-top-left-radius
    - outline
    - outline-width
    - outline-color
    - outline-style
    - outline-offset
    - overflow
    - overflow-x
    - overflow-y
    - resize
    - visibility
    - font
    - font-style
    - font-variant
    - font-weight
    - font-stretch
    - font-size
    - font-family
    - font-synthesis
    - font-size-adjust
    - font-kerning
    - line-height
    - text-align
    - text-align-last
    - vertical-align
    - text-overflow
    - text-justify
    - text-transform
    - text-indent
    - text-emphasis
    - text-emphasis-style
    - text-emphasis-color
    - text-emphasis-position
    - text-decoration
    - text-decoration-color
    - text-decoration-style
    - text-decoration-line
    - text-underline-position
    - text-shadow
    - white-space
    - overflow-wrap
    - word-wrap
    - word-break
    - line-break
    - hyphens
    - letter-spacing
    - word-spacing
    - quotes
    - tab-size
    - orphans
    - writing-mode
    - text-combine-upright
    - unicode-bidi
    - text-orientation
    - direction
    - text-rendering
    - font-feature-settings
    - font-language-override
    - image-rendering
    - image-orientation
    - image-resolution
    - shape-image-threshold
    - shape-outside
    - shape-margin
    - color
    - background
    - background-image
    - background-position
    - background-size
    - background-repeat
    - background-origin
    - background-clip
    - background-attachment
    - background-color
    - background-blend-mode
    - isolation
    - clip-path
    - mask
    - mask-image
    - mask-mode
    - mask-position
    - mask-size
    - mask-repeat
    - mask-origin
    - mask-clip
    - mask-composite
    - mask-type
    - filter
    - box-shadow
    - opacity
    - transform-style
    - transform
    - transform-box
    - transform-origin
    - perspective
    - perspective-origin
    - backface-visibility
    - transition
    - transition-property
    - transition-duration
    - transition-timing-function
    - transition-delay
    - animation
    - animation-name
    - animation-duration
    - animation-timing-function
    - animation-delay
    - animation-iteration-count
    - animation-direction
    - animation-fill-mode
    - animation-play-state
    - scroll-behavior
    - scroll-snap-type
    - scroll-snap-destination
    - scroll-snap-coordinate
    - cursor
    - touch-action
    - caret-color
    - ime-mode
    - object-fit
    - object-position
    - content
    - counter-reset
    - counter-increment
    - will-change
    - pointer-events
    - all
    - page-break-before
    - page-break-after
    - page-break-inside
    - widows
  order/order:
    - declarations
    - custom-properties
    - dollar-variables
    - rules
    - at-rules
ignoreFiles:
  - 'static/**'
  - '*.js'
  - '*.ts'
  - 'src/**/*.js'
  - 'src/**/*.ts'
